source 'https://cdn.jsdelivr.net/cocoa/'

platform :ios, '11.0'

target 'RakutenRanking' do

  pod 'SnapKit', '~> 4.0.0'
  pod 'DifferenceKit/UIKitExtension', '1.0.0'
  pod 'Nuke', '~> 7.0'

  pod 'common', :path => '../common'
end
