platform :ios, '11.0'

plugin 'cocoapods-keys', {
    :keys => [
        "RakutenAppId"
    ]
}

target 'RakutenRanking' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 4.0.0'
  pod 'DifferenceKit/UIKitExtension'
  pod 'Nuke', '~> 7.0'
end
