name: RakutenRanking
options:
  minimumXcodeGenVersion: 2.2.0
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 11.0
targets:
  RakutenRanking:
    platform: iOS
    type: application
    sources:
      - RakutenRanking
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ${inherited}
      INFOPLIST_FILE: RakutenRanking/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.github.watabee.RakutenRanking
      SWIFT_VERSION: 5.0
      VALID_ARCHS: arm64
schemes:
  RakutenRanking:
    build:
      targets:
        RakutenRanking: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
